In [1]:
import requests
from bs4 import BeautifulSoup
import re

In [2]:
# Define headers to mimic a browser request
headers ={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}

In [45]:
company_names = []
temp_company = []

In [46]:

file_path = 'list_items.txt'
# Open the file in read mode
with open(file_path, 'r') as file:
    # Read a single line from the file
    lines = file.readlines()
    
    for line in lines:
        company_names.append(line.strip())

In [47]:
M, N = 1000,1500
for i in range(M,N):
    ns = company_names[i].replace(" ","-")
    temp_company.append(ns)

In [48]:
len(temp_company)
# temp_company

500

In [49]:
len(company_names)

9980

In [50]:
company__ = []

In [51]:
iter=0

In [52]:
cleaned_strings_r = []
actual_slr = []
salary_min = []
salary_max = []
cleaned_strings = []
designation = []
exp_req = []
#revenue, rating, review, 
reviews = []
ratings = []

In [53]:
for company_name in temp_company:
    url = f'https://www.ambitionbox.com/salaries/{company_name}-salaries/'
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    divs_with_td = soup.find_all('tr', {'class': "jobProfiles-table__row"})

    # reinitializing to make it blank
    exp = []
    slr = []
    
    # Iterate through the <div> tags and find paragraphs within <td> tags
    for div in divs_with_td:
        td_tags = div.find_all('td', {'class':'left-content'})
        for td in td_tags:
            experience = td.find_all('div', {'class':'card-content'})
            for i in experience:
                s = i.get_text().replace('\t', '').replace('\n', '')
                exp.append(s)
    
    for i in range(len(exp)):
        cleaned_string = exp[i].replace('\xa0','').replace('Experience', '')
        clear_str = re.sub(r'\([^)]*\)', '', cleaned_string)
        cleaned_strings.append(clear_str)
        sec1, sec2 = cleaned_strings[i].split(':')
        designation.append(sec1)
        exp_req.append(sec2)
        company__.append(company_name)
        
    # Iterate through the <div> tags and find paragraphs within <td> tags
    for div in divs_with_td:
        td_tags = div.find_all('td', {'class':'right-content'})
        for td in td_tags:
            salary = td.find_all('div', {'class':'avg-salary'})
            for j in salary:
                s = j.get_text().replace('\t', '').replace('\n', '')
                slr.append(s)
    
    for i in range(len(slr)):
        try:
            s1,s2,s3 = re.findall(r'[\d,.]+', slr[i])
            actual_slr.append(s1)
            salary_min.append(s2)
            salary_max.append(s3)
        except:
            s1,s2,s3 = None, None, None
            actual_slr.append(s1)
            salary_min.append(s2)
            salary_max.append(s3)
        
    
    # scrap=2
    
    iter += 1
    url2 = f'https://www.ambitionbox.com/list-of-companies?page={iter}'
    response = requests.get(url2, headers=headers)
    soup2 = BeautifulSoup(response.content, 'html.parser')
        
    rt = soup2.find_all('div', class_='companyCardWrapper__companyRatingWrapper')
    for span in rt:
        try:
            r = (span.text).strip()
        except:
            r = None
    div_element = soup2.find_all('div', class_='companyCardWrapper__tertiaryInformation')
    for divs in div_element:
        try:
            span_element = divs.find('span', class_='companyCardWrapper__ActionCount')
        except:
            span_element = None
    # appending rewiew and rating
    for k in range(len(exp)):
        ratings.append(r)
        reviews.append(span_element.text)

In [ ]:
# Find all <td> tags within <div> tags
# divs_with_td = soup.find_all('tr', {'class': "jobProfiles-table__row"})

In [54]:
company__
len(ratings), len(reviews), len(slr), len(exp)

(4470, 4470, 0, 0)

In [ ]:
# # Iterate through the <div> tags and find paragraphs within <td> tags
# for div in divs_with_td:
#     td_tags = div.find_all('td', {'class':'left-content'})
#     for td in td_tags:
#         experience = td.find_all('div', {'class':'card-content'})
#         for i in experience:
#             s = i.get_text().replace('\t', '').replace('\n', '')
#             exp.append(s)

In [ ]:
# cleaned_strings = []
# designation = []
# exp_req = []
# for i in range(len(exp)):
#     cleaned_string = exp[i].replace('\xa0','').replace('Experience', '')
#     clear_str = re.sub(r'\([^)]*\)', '', cleaned_string)
#     cleaned_strings.append(clear_str)
#     s1, s2 = cleaned_strings[i].split(':')
#     designation.append(s1)
#     exp_req.append(s2)

In [ ]:
# # Iterate through the <div> tags and find paragraphs within <td> tags
# for div in divs_with_td:
#     td_tags = div.find_all('td', {'class':'right-content'})
#     for td in td_tags:
#         salary = td.find_all('div', {'class':'avg-salary'})
#         for j in salary:
#             s = j.get_text().replace('\t', '').replace('\n', '')
#             slr.append(s)

In [ ]:
# cleaned_strings_r = []
# actual_slr = []
# salary_min = []
# salary_max = []
# for i in range(len(exp)):
#     s1,s2,s3 = re.findall(r'[\d,.]+', slr[i])
#     actual_slr.append(s1)
#     salary_min.append(s2)
#     salary_max.append(s3)

## full dataset extraction

In [ ]:
# url2 = 'https://www.ambitionbox.com/list-of-companies?page=1'

In [ ]:
# response = requests.get(url2, headers=headers)

In [ ]:
# soup2 = BeautifulSoup(response.content, 'html.parser')

In [ ]:
#revenue, rating, review, profit
# reviews = []
# ratings = []

In [ ]:
# rt = soup2.find_all('div', class_='companyCardWrapper__companyRatingWrapper')

In [ ]:
# for span in rt:
#     r = (span.text).strip()
# ratings.append(r)

In [ ]:
# # Find the <div> element with the specified class
# div_element = soup2.find_all('div', class_='companyCardWrapper__tertiaryInformation')

# for divs in div_element:
#     span_element = divs.find('span', class_='companyCardWrapper__ActionCount')
# reviews.append(span_element.text)

## financial data gathering

## making DataFrame

In [55]:
import pandas as pd

In [56]:
dataset = [designation, company__ , exp_req, actual_slr, salary_min, salary_max, ratings, reviews]
cols = ['Designation', 'Company', 'experience', 'average salary', 'minimum salary', 'maximum salary', 'ratings', 'reviews']

In [57]:
df = pd.DataFrame(dataset, cols)

In [58]:
for q in dataset:
    print(len(q))

4470
4470
4470
4470
4470
4470
4470
4470

In [59]:
df = df.T

In [60]:
df.tail(20)

,Designation,Company,experience,average salary,minimum salary,maximum salary,ratings,reviews
4450,Officer,Magneti-Marelli-Motherson-Auto-System,1-7yrs,"2,72,565",1.1,5.1,4.1,62
4451,Junior Officer,Magneti-Marelli-Motherson-Auto-System,1-5yrs,"2,80,012",1.2,4.1,4.1,62
4452,Production Officer,Magneti-Marelli-Motherson-Auto-System,1-6yrs,"2,20,236",1.0,4.0,4.1,62
4453,Executive Production,Magneti-Marelli-Motherson-Auto-System,5-13yrs,"2,07,223",1.2,3.3,4.1,62
4454,QC Officer,Magneti-Marelli-Motherson-Auto-System,1-6yrs,"1,69,416",1.0,2.4,4.1,62
4455,Scientist 1,Magneti-Marelli-Motherson-Auto-System,2-6yrs,"4,73,712",3.2,7.2,4.1,62
4456,Deputy Manager,Magneti-Marelli-Motherson-Auto-System,8-16yrs,"1,70,442",1.0,3.1,4.1,62
4457,Junior Production Officer,Magneti-Marelli-Motherson-Auto-System,1-3yrs,"2,17,558",1.1,3.2,4.1,62
4458,Process Engineer,Magneti-Marelli-Motherson-Auto-System,1-7yrs,"1,58,767",1.0,2.2,4.1,62
4459,EHS Officer,Magneti-Marelli-Motherson-Auto-System,1-7yrs,"3,55,893",1.8,5.0,4.1,62
4460,Officer,TVS-Electronics,1-7yrs,"2,47,112",1.4,4.1,4.2,62
4461,Junior Officer,TVS-Electronics,1-5yrs,"2,63,433",1.1,4.0,4.2,62
4462,Production Officer,TVS-Electronics,1-6yrs,"2,62,902",1.4,3.8,4.2,62
4463,Executive Production,TVS-Electronics,5-13yrs,"2,61,573",1.2,3.6,4.2,62
4464,QC Officer,TVS-Electronics,1-6yrs,"3,88,695",2.6,5.5,4.2,62
4465,Scientist 1,TVS-Electronics,2-6yrs,"3,42,129",1.8,5.0,4.2,62
4466,Deputy Manager,TVS-Electronics,8-16yrs,"1,82,500",25.0,2.5,4.2,62
4467,Junior Production Officer,TVS-Electronics,1-3yrs,"4,64,189",3.8,6.5,4.2,62
4468,Process Engineer,TVS-Electronics,1-7yrs,"2,27,045",50.0,3.9,4.2,62
4469,EHS Officer,TVS-Electronics,1-7yrs,"8,60,238",5.5,16.0,4.2,62

In [61]:
df.head(20)

,Designation,Company,experience,average salary,minimum salary,maximum salary,ratings,reviews
0,Officer,Hikal,1-7yrs,"3,98,276",2.2,5.8,3.6,14.7k
1,Junior Officer,Hikal,1-5yrs,"3,05,526",2.0,3.9,3.6,14.7k
2,Production Officer,Hikal,1-6yrs,"3,49,344",2.2,5.3,3.6,14.7k
3,Executive Production,Hikal,5-13yrs,"6,45,371",4.0,8.3,3.6,14.7k
4,QC Officer,Hikal,1-6yrs,"3,53,688",2.6,4.7,3.6,14.7k
5,Scientist 1,Hikal,2-6yrs,"4,40,564",3.0,5.7,3.6,14.7k
6,Deputy Manager,Hikal,8-16yrs,"12,08,714",6.9,17.5,3.6,14.7k
7,Junior Production Officer,Hikal,1-3yrs,"2,85,277",2.0,3.7,3.6,14.7k
8,Process Engineer,Hikal,1-7yrs,"5,64,978",3.6,9.0,3.6,14.7k
9,EHS Officer,Hikal,1-7yrs,"3,98,604",2.7,5.4,3.6,14.7k
10,Officer,Visionary-RCM-Infotech,1-7yrs,"3,46,968",1.0,8.4,4.3,6.3k
11,Junior Officer,Visionary-RCM-Infotech,1-5yrs,"3,23,783",15.0,5.0,4.3,6.3k
12,Production Officer,Visionary-RCM-Infotech,1-6yrs,"5,22,683",1.8,8.0,4.3,6.3k
13,Executive Production,Visionary-RCM-Infotech,5-13yrs,"2,96,737",1.3,5.0,4.3,6.3k
14,QC Officer,Visionary-RCM-Infotech,1-6yrs,"5,38,199",3.1,7.8,4.3,6.3k
15,Scientist 1,Visionary-RCM-Infotech,2-6yrs,"3,27,378",1.2,5.6,4.3,6.3k
16,Deputy Manager,Visionary-RCM-Infotech,8-16yrs,"3,41,068",1.2,4.4,4.3,6.3k
17,Junior Production Officer,Visionary-RCM-Infotech,1-3yrs,"6,58,243",3.3,8.5,4.3,6.3k
18,Process Engineer,Visionary-RCM-Infotech,1-7yrs,"4,53,316",2.5,5.5,4.3,6.3k
19,EHS Officer,Visionary-RCM-Infotech,1-7yrs,"4,19,913",2.0,6.3,4.3,6.3k

In [62]:
df['Company'].unique()

array(['Hikal', 'Visionary-RCM-Infotech', 'SNC-Lavalin', 'HT-Media',
       'Shriram-General-Insurance', 'GVPR-Engineers',
       'Allianz-Technology', 'Fusion-Microfinance',
       'Acme-Cleantech-Solutions', 'Mswipe-Technologies',
       'Parekh-Integrated-Services', 'Precision-Techserve',
       'Acuity-Knowledge-Partners', 'Vertiv', 'Samasta-Microfinance',
       'Duck-Creek-Technologies', 'Air-India-Sats-Airport-Services',
       'Bechtel', 'Micromax-Informatics', 'Samsung-Engineering',
       'VeeTechnologies', 'Mu-Sigma', 'United-Breweries', 'Skill-Lync',
       'Medha-Servo-Drives', 'Godfrey-Phillips-India',
       'Everest-Industries', 'Willis-Towers-Watson', 'Fareportal',
       'PayPal', 'Wheels', 'Samsung-Electronics-Corporation',
       'Godrej-Agrovet', 'CRB-Tech-Solution', 'Atlas-Copco',
       'Natco-Pharma', 'Gharda-Chemicals', 'Knorr-Bremse',
       'Renew-Solar-Power', 'Sri-Chaitanya-Schools',
       'Sandhar-Technologies', 'Orchids-International-School',
       'Rashmi-Metaliks', 'Aristo-Pharmaceuticals', 'Softenger',
       'Amara-Raja-Group', 'DuPont', 'Star-Cement', 'Indira-IVF-Hospital',
       'Centre-for-Development-of-Advanced-Computing',
       'Suzuki-Motorcycle', 'DLF', 'Federal-Bank', 'Greenko-Group',
       'Varroc-Polymers', 'Prodapt', 'Kotak-Mahindra-Prime',
       'GlaxoSmithKline-Consumer-Healthcare', 'National-Health-Mission',
       'Telenor', 'Aarvi-Encon', 'Page-Industries',
       'Lakshmi-Machine-Works', 'Medlife', 'Timken',
       'Test-Yantra-Software-Solutions', 'General-Mills', 'Rupeek',
       'Kohler', 'Artech-Infosystems', 'Leadec-India',
       'Capital-Numbers-Infotech', 'DAV-Public-School', 'Aspire-Systems',
       'Otis-Elevator', 'More-Supermarket', 'Medusind-Solutions',
       'Aparna-Constructions-and-Estates', 'IDFC-FIRST-Bharat',
       'Michelin', 'ValueMomentum', 'Sanden-Vikas',
       'Navayuga-Engineering-Company', 'Pristyn-Care',
       'Carnival-Cruise-Lines', 'Allscripts', 'Webhelp', 'Pacific-BPO',
       'SFO-Technologies', 'LEAD-School', 'Kalpataru-Group',
       'Musashi-Auto-Parts', 'Genpact-Headstrong-Capital-Markets',
       'OCS-Group', 'OLX', 'Grant-Thornton', 'GirnarSoft',
       'Reliance-Power', 'ICCS', 'ICA-Edu-Skills', 'Aditya-Birla-Finance',
       'Schlumberger', 'Capri-Global-Capital', 'Temenos',
       'Sheenlac-Paints', 'Ugam-Solution', 'NetAmbit', 'Amazon-Services',
       'Steag-Energy-Services', 'Royal-Sundaram-General-Insurance',
       'Netscribes', 'Kurlon', 'Indiabulls-Ventures',
       'J-B-Chemicals-And-Pharmaceuticals', 'Tanishq', 'Velocis-Systems',
       'NBC-Bearings', 'Dunzo', 'Asirvad-Microfinance',
       'Collins-Aerospace', 'Stanza-Living', 'Tata-Starbucks',
       'The-Lalit', 'Tata-Consumer-Products', 'Volvo', 'Nityo-Infotech',
       'Signify', 'Arohan-Financial-Services', 'NetCracker',
       'Eveready-Industries', 'Flash-Electronics', 'Sagility',
       'Crowne-Plaza', 'Knight-Frank', 'Lumen-Technologies',
       'Shilpa-Medicare', 'Aparajitha-Corporate-Services',
       'Bharti-Infratel', 'Westside', 'Kutumbh-Care', 'Xebia',
       'Jio-Platforms', 'NoBrokerHOOD', 'Magna-Infotech',
       'bnp-paribas-india-solutions', 'Investors-Clinic',
       'Lumina-Datamatics', 'CNH-Industrial', 'First-Advantage',
       'Jaya-Hind-Industries', 'GE-Healthcare',
       'Trimax-IT-Infrastructure-Services', 'IMPACT-Infotech', 'HomeLane',
       'Rallis-India', 'Electrosteel-Steels', 'City-Union-Bank',
       'Hitachi-Systems-Micro-Clinic', 'CreditAccess-Grameen',
       'Deepak-Fertilisers-and-Petrochemicals', 'Advik-Hi-Tech', 'Denave',
       'EMERSON-PROCESS-MANAGEMENT', 'Rebel-Foods',
       'RAMTeCH-Software-Solutions', 'Bitwise-Solutions',
       'Caparo-Engineering-India', 'Redington',
       'AuthBridge-Research-Services', 'Adani-Green-Energy',
       'Chennai-Radha-Engineering-Works', 'Engineers-India', 'Religare',
       'Salesforce', 'Primus-Global-Technologies', 'Eris-Lifesciences',
       'Dhani-Loans-and-Services', 'TCNS-Clothing-Company',
       'Ingram-Micro', 'Innodata-Isogen', 'McDermott-International',
       'Globant', 'Finolex-Cables', 'Svatantra-Microfin',
       'Rodic-Consultants', 'Neeyamo-Enterprise-Solutions',
       'Apollo-Munich-Health-Insurance', 'Lea-Associates-South-Asia',
       'Sharda-Motor-Industries', 'Ukb-Electronics',
       'NTT-DATA-Business-Solutions', 'IFFCO', 'Jain-Irrigation-Systems',
       'Adani-Enterprises', 'HSBC-Bank', 'GSK-Pharmaceuticals',
       'Biba-Apparels', 'Ameriprise-Financial', 'Indo-Autotech',
       'Ihg-Group', 'Amphenol-Interconnect', 'Citco', 'Mastek',
       'Ashirvad-Pipes', 'Guardian-India', 'ffreedom-app',
       'Pratap-Technocrats', 'TDK-India', 'Raychem-RPG',
       'Muthoot-Microfin', 'Comviva-Technology', 'FIITJEE',
       'Royal-Caribbean-International', 'Sintex-Industries',
       'ANZ-Banking-Group', 'Isuzu-Motors', 'Jabil-Circuit-India',
       'Edubridge-Learning', 'Ramco-Systems', 'Government-of-India',
       'United-Spirits', 'Ups-Logistics', 'Bses-Rajdhani-Power',
       'Sl-Lumax', 'Progressive-Infotech', 'Rico-Auto-Industries',
       'Union-Bank-of-India', 'Xceedance', 'Zydus-Wellness', 'Skipper',
       'Astral-Pipe', 'MattsenKumar', 'Fractal-Analytics', 'PUMA',
       'Omaxe', 'VA-Tech-Wabag', 'Target', 'Epsilon', 'HCL-Comnet',
       'Epicenter-Technologies', 'Ag-Industries', 'OMICS-International',
       'Integreon', 'Sadbhav-Engineering', 'Vakrangee',
       'Shaktiman-Tirth-Agro-Technology', 'Rohan-Builders', 'Simplilearn',
       'Future-Lifestyle-Fashion', 'AVEVA', 'Times-Internet',
       'Fleetguard-Filters', 'Rentokil-Pest-Control',
       'Amway-India-Enterprises', 'Thriveni-Earthmovers',
       'ZUVENTUS-HEALTHCARE', 'Tata-Hitachi-Construction-Machinery',
       'Quatrro', 'Mott-MacDonald', 'Bioclinica', 'Bpo-Convergence',
       'NielsenIQ', 'India-Cements', 'Linde-India',
       'Central-Industrial-Security-Force', 'NSB-Bpo-Solutions',
       'Somany-Ceramics', 'Toyo-Engineeering', 'Merino-Industries', 'GKN',
       'SitusAMC', 'Naukri', 'MagicBricks', 'Creambell',
       'Deccan-Fine-Chemicals', 'Adani-Solar', 'Wonder-Cement',
       'Vijaya-Diagnostic-Centre', 'Northern-Trust',
       'Baxter-International', 'Alshaya-Group', 'KGISL', 'General-Motors',
       'KaaShiv-InfoTech-Company', 'BASF', 'Bikanervala',
       'Diebold-Nixdorf', 'LifeCell-International',
       'Lionbridge-Technologies', 'Csc-E-Governance-Services', 'Accolite',
       'Citigroup', 'Encore-Capital-Group', 'India-Japan-Lighting',
       'Mount-Litera-Zee-School', 'India-Shelter-Finance-Corporation',
       'Sun-Life-Financial', 'Experis-IT', 'Hella', 'Prism-Johnson',
       'SHYAM-METALICS-AND-ENERGY', 'MasterCard',
       'Lovely-Professional-University', 'Balkrishna-Industries',
       'JK-Paper', 'Saud-Bahwan-Group', 'Radical-Minds', 'Quikr',
       'Care-Hospital', 'Parag-Milk-Foods',
       'SoftAge-Information-Technology', 'Titan-Eye-Plus',
       'Educomp-Solutions', 'Electrotherm', 'Mindarika',
       'Astral-Adhesives', 'Icon-Plc', 'Micro-Turners',
       'Magna-International', 'K-Raheja-Corp', 'Sunbeam-Auto',
       'Border-Security-Force', 'Aisin-Automotive-Haryana',
       'KMV-Projects', 'Tata-Power-Delhi-Distribution',
       'Tavant-Technologies', 'Courtyard-by-Marriott', 'Turbo-Energy',
       'BEML', 'AVTEC', 'Shivam-Autotech', 'Wapcos', 'Saudi-Aramco',
       'Wuerth', 'Molex', 'Geojit-Financial-Services', 'ACL-Digital',
       'IBS-Software-Services', 'Ge-India-Industrial', 'NRB-Bearings',
       'Aerial-Telecom-Solutions', 'Mynd-Solutions-Private', 'SKH-Metals',
       'Ramky-Infrastructure', 'MALABAR-GOLD-AND-DIAMONDS',
       'Vivanta-by-Taj', 'Dhani-Healthcare', 'Poly-Medicure',
       'PeopleStrong', 'Hilton', 'Medreich',
       'Quantiphi-Analytics-Solutions', 'Inox-Wind', 'Vijay-Sales',
       'Orient-Electric', 'MAS-Financial-Services', 'IVY-Comptech',
       'Progressive-Infovision', 'Jaro-Education',
       'Steel-Authority-Of-India', 'Hapag-Lloyd', 'HIL', 'uFaber',
       'BT-E-Serv', 'Accel-Frontline', 'Dhanuka-Agritech',
       'Ongc-Petro-Additions', 'National-Informatics-Centre',
       'Times-Group', 'Atkins', 'Hitachi', 'Aequs', 'Affinity-Express',
       'Renault', 'Orient-Cement', 'Goodyear', 'JSW-Group',
       'Amazon-Web-Services', 'Poorvika-Mobiles',
       'Thermo-Fisher-Scientific', 'House-Of-Anita-Dongre',
       'Hi-Tech-Gears', 'Chandigarh-University', 'Travel-Food-Services',
       'Kantar', 'Nlb-Services', 'Neuland-Laboratories',
       'ATS-Infrastructure', 'Holiday-Inn', 'Apar-Industries',
       'Principal-Global-Services', 'Microtek-International',
       'Medicover-Hospitals', 'Orient-Craft',
       'McNally-Bharat-Engineering', 'Genesys-International-Corporation',
       'Samunnati-Financial-Intermediation-and-Services', 'MG-Motor',
       'Physicswallah', 'Akal-Information-Systems', 'Centum-Learning',
       'Credence-Resource-Management', 'HBL-Power-Systems',
       'United-Colors-of-Benetton', 'My-Home-Industries',
       'Jubilant-Generics', 'Teamware-Solutions', 'DP-World', 'Yatra',
       'Qatar-Airways', 'Navitasys-India', 'Cigniti-Technologies',
       'Saint-Gobain-Glass', 'BankBazaar', 'Vadilal-Industries',
       'Digit-Insurance', 'Renovision-Automation-Services',
       'Writer-Corporation', 'Central-Reserve-Police-Force',
       'Action-Construction-Equipment', 'Schindler-Group', 'Greenply',
       'Jyothy-Laboratories', 'Shyam-Steel-Industries',
       'Cloudnine-Hospital', 'Sutherland-Healthcare-Solutions',
       'CDK-Global', 'Expleo-Solutions', 'Hilti', 'Amadeus', 'Embibe',
       'Ask-Automotive', 'Maveric-Systems', 'Surya-Roshni',
       'Dimension-Data', 'Sterlite-Power-Transmission', '3M',
       'Forbes-Marshall', 'TTK-Prestige', 'V-Trans',
       'Magneti-Marelli-Motherson-Auto-System', 'TVS-Electronics'],
      dtype=object)

In [63]:
# Save the DataFrame to a CSV file
csv_filename = 'AmbitionBox_Data_v5.csv'
df.to_csv(csv_filename, index=False)

print(f"DataFrame saved to {csv_filename}")

DataFrame saved to AmbitionBox_Data_v5.csv